version: '3'
services:
  database:
    image: mariadb:10.0.36
    volumes:
      - "./.docker/data/db:/var/lib/mysql"
      - "./.docker/config/db:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    restart: always
  memcached:
    image: memcached:alpine
    restart: always
    command: -m 128
  php:
    image: peterbooker/phpwp:7.2-fpm
    depends_on:
      - database
      - memcached
    working_dir: /var/www/html
    volumes:
      - "./.docker/wordpress:/var/www/html"
      - "./.docker/config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "./.docker/config/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    extra_hosts:
      - "wp.local.com:172.18.0.1"
    restart: always
  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  nginx:
    image: nginx:latest
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./.docker/wordpress:/var/www/html"
      - "./.docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./.docker/config/certs:/etc/nginx/certs"
    restart: always