version: '3'
services:
  database:
    image: mariadb:${DB_VERSION:-10.3}
    volumes:
      - "./.docker/data/db:/var/lib/mysql"
      - "./.docker/config/db:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    restart: always
    command:
      'mysqld --innodb-flush-method=fsync'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: password
      PMA_ABSOLUTE_URI: http://phpmyadmin.localhost
    restart: always
  memcached:
    image: memcached:alpine
    restart: always
    command: -m 128
  php:
    image: peterbooker/phpwp:${PHP_VERSION:-7.2}-fpm
    depends_on:
      - database
      - memcached
    working_dir: /var/www/html
    volumes:
      - "./.docker/wordpress:/var/www/html"
      - "./.docker/config/php/php.ini:/usr/local/etc/php/php.ini"
    extra_hosts:
      - "localhost:172.18.0.1"
    restart: always
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
  caddy:
    image: abiosoft/caddy
    volumes:
      - "./.docker/config/caddy/Caddyfile:/etc/Caddyfile"
      - "./.docker/wordpress:/var/www/html"
    ports:
      - "80:80"
      - "443:443"