version: '3'
services:
  database:
    image: mariadb:${DB_VERSION:-10.3}
    volumes:
      - "./.docker/data/db:/var/lib/mysql"
      - "./.docker/config/db:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_DATABASE:-wordpress}
      MYSQL_USER: ${DB_USER:-wordpress}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    restart: always
    command:
      'mysqld --innodb-flush-method=fsync'
  adminer:
    image: adminer:fastcgi
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database
    restart: always
  memcached:
    image: memcached:alpine
    restart: always
    command: -m 128
  php:
    image: peterbooker/phpwp:${PHP_VERSION:-7.2}-fpm
    depends_on:
      - database
      - memcached
    working_dir: /var/www/html
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-wordpress}
      MYSQL_USER: ${DB_USER:-wordpress}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      WP_VERSION: ${WP_VERSION:-latest}
      WP_USER: ${WP_USER:-user}
      WP_PASSWORD: ${WP_PASSWORD:-password}
      WP_EMAIL: ${WP_EMAIL:-user@localhost.com}
    volumes:
      - "./.docker/wordpress:/var/www/html"
      - "./.docker/config/php/php.ini:/usr/local/etc/php/php.ini"
    extra_hosts:
      - "localhost:172.18.0.1"
    restart: always
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
  caddy:
    image: abiosoft/caddy
    volumes:
      - "./.docker/config/caddy/Caddyfile:/etc/Caddyfile"
      - "./.docker/wordpress:/var/www/html"
    ports:
      - "80:80"
      - "443:443"