version: '3'
services:
  database:
    image: mysql:5
    volumes:
      - "./.docker/data/db:/var/lib/mysql"
      - "./.docker/config/db:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    restart: always
  memcached:
    image: memcached:alpine
    restart: always
    command: -m 128
  php:
    build: peterbooker/php:php7.2-fpm-alpine
    depends_on:
      - database
      - memcached
    working_dir: /var/www/html
    volumes:
      - "./.docker/wordpress:/var/www/html"
      - "./.docker/config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
    restart: always
  nginx:
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    image: nginx:latest
    volumes:
      - "./.docker/wordpress:/var/www/html"
      - "./.docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./.docker/config/certs:/etc/nginx/certs"
    restart: always